name: enem-questions

services:

  nginx:
    image: 'nginx:1.25.5'
    container_name: nginx_container
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"
    networks:
      - proxy
    depends_on:
      - backend
      - frontend

  postgres:
    image: 'postgres:alpine3.19'
    container_name: postgres_container
    ports:
      - 8083:5432
    networks:
      - proxy
    environment:
      - POSTGRES_DB=enem-questions
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /enem-questions-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "enem-questions" ]
      interval: 1s
      retries: 5

  redis:
    image: 'redis:alpine3.19'
    container_name: redis_container
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD_VALUE}"
    environment:
      REDIS_PASSWORD_VALUE: ${REDIS_PASSWORD}
    ports:
      - 8084:6379
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1s
      retries: 5

  backend:
    build:
      dockerfile: ./back-end/Dockerfile
    container_name: backend_container
    ports:
      - 8080:8080
    networks:
      - proxy
    environment:
      db-url: jdbc:postgresql://postgres:5432/enem-questions
      db-username: ${POSTGRES_USERNAME}
      db-password: ${POSTGRES_PASSWORD}
      redis-host: localhost
      redis-port: 8084
      redis-password: ${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      dockerfile: ./front-end/Dockerfile
    container_name: frontend_container
    ports:
      - 8081:8080
    networks:
      - proxy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started

networks:
  proxy:
    driver: bridge

volumes:
  enem-questions-volume:
    external: false
