name: enem-questions

services:
  nginx:
    image: 'nginx:1.25.5'
    container_name: nginx_container
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started

  postgres:
    image: 'postgres:alpine3.19'
    container_name: postgres_container
    ports:
      - 5432:5432
    networks:
      - proxy
    environment:
      - POSTGRES_DB=enem-questions
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /enem-questions-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "enem-questions" ]
      interval: 1s
      retries: 5

  redis:
    image: 'redis:alpine3.19'
    container_name: redis_container
    command: redis-server --requirepass ${REDIS_PASSWORD}
    hostname: localhost
    ports:
      - 6379:6379
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1s
      retries: 5

  backend:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
    container_name: backend_container
    networks:
      - proxy
    environment:
      db-url: jdbc:postgresql://postgres:5432/enem-questions
      db-username: ${POSTGRES_USERNAME}
      db-password: ${POSTGRES_PASSWORD}
      redis-host: redis
      redis-port: 6379
      redis-password: ${REDIS_PASSWORD}
      jwt-secret: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    container_name: frontend_container
    networks:
      - proxy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  proxy:
    driver: bridge

volumes:
  enem-questions-volume:
    external: false
