name: enem-questions

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_container
    ports:
      - 8083:5432
    environment:
      - POSTGRES_DB=enem-questions
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /enem-questions-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "enem-questions" ]
      interval: 5s
      retries: 5

  redis:
    image: 'redis:latest'
    container_name: redis_container
    ports:
      - 8084:6379
    environment:
      - REDIS_HOST=localhost
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  backend:
    build:
      dockerfile: ./back-end/Dockerfile
    container_name: backend_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://postgres:5432/enem-questions
      db-username: ${POSTGRES_USERNAME}
      db-password: ${POSTGRES_PASSWORD}
      redis-host: localhost
      redis-port: 8084
      redis-password: ${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      dockerfile: ./front-end/Dockerfile
    container_name: frontend_container
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  enem-questions-volume:
    external: false
