name: Build Backend Image

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Back-end image
      run: docker build back-end/ --file Dockerfile --tag enem-questions-backend:$(date +%s)
    - name: Build the Front-end image
      run: docker build front-end/ --file Dockerfile --tag enem-questions-frontend:$(data +%s)
